//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raiz.Deployment.Persistencia
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Raiz.Deployment.DTO;
    
    
    public partial class RAIZLOGEntities : DbContext
    {
        public RAIZLOGEntities()
            : base("name=RAIZLOGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Menu> TBMRaizNetMenu { get; set; }
        public DbSet<Modulo> TBMRaizNetModulo { get; set; }
        public DbSet<PubComponente> TBMRaizNetPubComponente { get; set; }
    }
}
