//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raiz.Deployment.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int idMenu { get; set; }
        public string displayName { get; set; }
        public string Descripcion { get; set; }
        public string formulario { get; set; }
        public string componente { get; set; }
        public Nullable<int> idMenuPadre { get; set; }
        public Nullable<bool> estado { get; set; }
    }
}
