//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raiz.Deployment.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulo
    {
        public int idModulo { get; set; }
        public string nombreModulo { get; set; }
        public string descripcion { get; set; }
        public string formatoVersion { get; set; }
        public Nullable<bool> estado { get; set; }
    }
}
