//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raiz.Deployment.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PubComponente
    {
        public int idPublicacion { get; set; }
        public string componente { get; set; }
        public Nullable<int> idModulo { get; set; }
        public string version { get; set; }
        public Nullable<bool> descargaObligatoria { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
    }
}
